site_name: 'Solinftec'
site_description: 'Reconhecimento de carreta mediante QrCode'
site_author: 'Gabriel Mauly'

theme:
  name: 'material'
  palette:
    primary: 'light blue'
    accent: 'orange'
  language: 'pt'

plugins:
    - search
    - pdf-export

markdown_extensions:
  - codehilite

